### ISSUE TITLE
clock problem

### ISSUE THREAD

**Issue by jimingda** [robotology/find-superquadric#8]
Hi,

After launch the `yarpserver`, i directly launch the command `find-superquadric --remove-outliers "(0.01 10)" --random-sample 0.2 --file ./data/cylinder`, and maybe get a similar problem as before. [#656](https://github.com/orgs/robotology/discussions/656)
```
icub@icubsrv:~/workspace/find-superquadric/build$ find-superquadric --remove-outliers "(0.01 10)" --random-sample 0.2 --file ./data/cylinder
[INFO] |yarp.os.Port|/icubsrv/find-superquadric/219478/clock:i| Port /icubsrv/find-superquadric/219478/clock:i active at tcp://192.168.101.128:10002/
[INFO] |yarp.os.Network| Success: port-to-port persistent connection added.
[ERROR] |yarp.os.NetworkClock| Cannot find time port "/clock" or a time topic "/clock@"
[INFO] |yarp.os.Time| Waiting for clock server to start broadcasting data ...
[INFO] |yarp.os.Time| Waiting for clock server to start broadcasting data ...
[INFO] |yarp.os.Time| Waiting for clock server to start broadcasting data ...
```

Thanks in advance.

**Comment by pattacini** [comment]
Hi @jimingda 

This has nothing to do with this module in particular.
`find-superquadric` doesn't even have an XML application.

I consider this issue off-topic then.

The problem with the clock is always the same.
My suggestion to keep things simpler is to remove the environment variable.

**Comment by jimingda** [comment]
Thanks @pattacini 
After disable the env variable  `#export YARP_CLOCK=/clock` in `~/.bashrc`
It works now.
