### ISSUE TITLE
the meaning of red part outside the object

### ISSUE THREAD

**Issue by jimingda** [robotology/find-superquadric#9]
Hi, 

As showed in the demo, there is a red area outside the object, and it keeps a fixed distance to the object, what does it stand for?
![2023-10-20_10-47](https://github.com/robotology/find-superquadric/assets/7019692/f8e9228a-9df2-449e-bcdf-2c7ddd0e54d4)

**Comment by pattacini** [comment]
Hi @jimingda 

Before optimizing for a superquadric, this tool polishes up the point cloud by identifying and removing outliers using a method called [DBSCAN](https://en.wikipedia.org/wiki/DBSCAN).

Therefore, those red points are exactly the outliers that are removed and thus not considered as part of the object to be modeled.

**Comment by pattacini** [comment]
I've added the link to DBSCAN also from within the main README.

**Comment by pattacini** [comment]
Closing.
Feel free to open it up again if required.
